function summaryTable = summarize_training_run(env, trainingStats, runName)

    N = 1000;

    nEpisodes = numel(env.meanDistEpisode);
    idxStart = max(1, nEpisodes - N + 1);
    idx = idxStart:nEpisodes;

    % ===== Reward promedio final =====
    avgRewardFinal = NaN;
    if istable(trainingStats)
        vars = trainingStats.Properties.VariableNames;
        if ismember('AverageReward', vars)
            avgRewardFinal = trainingStats.AverageReward(end);
        end
    end

    % ===== Q0 final =====
    q0Final = NaN;
    if istable(trainingStats)
        vars = trainingStats.Properties.VariableNames;
        if ismember('EpisodeQ0', vars)
            q0Final = trainingStats.EpisodeQ0(end);
        elseif ismember('Q0', vars)
            q0Final = trainingStats.Q0(end);
        end
    end

    % ===== Promedios últimos 1000 episodios =====
    madLast1000 = mean(env.meanDistEpisode(idx), 'omitnan');
    mseLast1000 = mean(env.mseEpisode(idx), 'omitnan');
    successLast1000 = mean(env.successRateEpisode(idx), 'omitnan');

    finalMeanAbsErrLast1000 = mean(env.finalMeanAbsErrEpisode(idx), 'omitnan');
    finalMaxAbsErrLast1000  = mean(env.finalMaxAbsErrEpisode(idx), 'omitnan');

    nearSuccessPctLast1000 = 100 * mean(env.nearSuccessEpisodeHistory(idx), 'omitnan');

    summaryTable = table( ...
        string(runName), ...
        avgRewardFinal, ...
        q0Final, ...
        madLast1000, ...
        mseLast1000, ...
        successLast1000, ...
        finalMeanAbsErrLast1000, ...
        finalMaxAbsErrLast1000, ...
        nearSuccessPctLast1000, ...
        'VariableNames', { ...
            'RunName', ...
            'AverageRewardFinal', ...
            'Q0Final', ...
            'MAD_Last1000', ...
            'MSE_Last1000', ...
            'SuccessRate_Last1000', ...
            'FinalMeanAbsErr_Last1000', ...
            'FinalMaxAbsErr_Last1000', ...
            'NearSuccessPct_Last1000' ...
        } ...
    );
end
